### PR TITLE
Update install script for GitHub review

### PR DESCRIPTION
**Pull request by danhunsaker**
Forgot to adjust the script to avoid the race condition of the new file being redirected into while also used as a source.

### CODE REVIEW

**Comment by sanderson** [comment]
Thanks @danhunsaker! I've been meaning to get back to this but have been wrapped up in other things.

**Comment by danhunsaker** [comment]
Yeah, I was meaning to submit these changes, too, at some point. The internal project I just started on was a good opportunity to poke at all these things, since Laravel is my quickest "0-60" framework.

**Comment by sanderson** [comment]
Awesome! Did you use this branch of the qs to do it? How did it go?

**Comment by danhunsaker** [comment]
Effectively, yeah. Downloaded the files into place, made the tweaks I then PR'd, and ran `nanobox run` to ensure it worked. Which it did, perfectly.

**Pull request merged**
